/root/.cargo/bin/lighthouse bn \
  --debug-level=info \
  --datadir=./consensus-data \
  --testnet-dir=./el-cl-genesis-data/custom_config_data \
  --listen-address=0.0.0.0 \
  --port=11011 \
  --http \
  --http-address=0.0.0.0 \
  --http-port=5111 \
  --http-allow-sync-stalled \
  --slots-per-restore-point=32 \
  --disable-packet-filter \
  --execution-endpoints=http://127.0.0.1:8562 \
  --jwt-secrets=./el-cl-genesis-data/jwt/jwtsecret \
  --suggested-fee-recipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776 \
  --subscribe-all-subnets \
  --import-all-attestations \
  --metrics \
  --metrics-address=0.0.0.0 \
  --metrics-allow-origin=* \
  --metrics-port=5164 \
  --enable-private-discovery=true \
  --target-peers=16 \
  --boot-nodes=enr:-LW4QI0Be6a0ELTXagGbdDELovP7XNpiYhM9_0yGi2pWCfwoMKQhELayRqnfmJeMWRj7afOoczn0POHLt7eElRdSqUABh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDT1PoxQAAAOP__________gmlkgnY0hHF1aWOCKvmJc2VjcDI1NmsxoQMlzn14FYiqER-tVJOOiB-nl9Z3pLreEg1SbT2H2y_XPYhzeW5jbmV0cwCDdGNwgir4