version: "3.8"

services:
  execution:
    image: ethpandaops/geth:master-5b57727
    command:
      - --networkid=38256
      - --state.scheme=path
      - --verbosity=3
      - --datadir=/execution-data
      - --http
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api=admin,engine,net,eth,web3,debug
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.api=admin,engine,net,eth,web3,debug
      - --ws.origins=*
      - --allow-insecure-unlock
      - --nat=extip:${IP_ADDRESS}
      - --verbosity=3
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/el-cl-genesis-data/jwt/jwtsecret
      - --syncmode=full
      - --rpc.allow-unprotected-txs
      - --metrics
      - --metrics.addr=0.0.0.0
    volumes:
      - ./execution-data:/execution-data
      - ./el-cl-genesis-data:/el-cl-genesis-data
    # ports:
    #   - "10545:8545" 
    #   - "10546:8546" 
    #   - "10551:8551" 
    #   - "11001:9001" 
    #   - "50303:50303/udp"
    #   - "50303:50303/tcp"
    restart: unless-stopped
    network_mode: host

  beacon:
    image: ethpandaops/lighthouse:proposer-signature-cache-c59fa34
    command:
      - lighthouse
      - beacon_node
      - --debug-level=info
      - --datadir=/consensus-data
      - --testnet-dir=/el-cl-genesis-data/custom_config_data
      - --disable-enr-auto-update
      - --enr-address=${IP_ADDRESS}
      - --listen-address=0.0.0.0
      - --http
      - --http-address=0.0.0.0
      - --execution-endpoints=http://execution:8551
      - --jwt-secrets=/el-cl-genesis-data/jwt/jwtsecret
      - --suggested-fee-recipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776
      - --subscribe-all-subnets
      - --import-all-attestations
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
    volumes:
      - ./consensus-data:/consensus-data 
      - ./el-cl-genesis-data:/el-cl-genesis-data
    # ports:
    #   - "9000:9000/udp"
    #   - "9000:9000/tcp"
    #   - "4200:4000"
    #   - "5254:5054"
    depends_on:
      - execution
    restart: unless-stopped
    network_mode: host

  validator:
    image: ethpandaops/lighthouse:proposer-signature-cache-c59fa34
    command:
      - lighthouse
      - validator_client
      - --debug-level=info
      - --testnet-dir=/el-cl-genesis-data/custom_config_data
      - --validators-dir=/validator_keys
      - --init-slashing-protection
      - --http
      - --unencrypted-http-transport
      - --http-address=0.0.0.0
      - --beacon-nodes=http://beacon:4000
      - --suggested-fee-recipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
    volumes:
      - ./el-cl-genesis-data:/el-cl-genesis-data
      - ./validator_keys:/validator_keys
    # ports:
    #   - "7062:5062"
    #   - "7063:5063"
    depends_on:
      - beacon
    restart: unless-stopped
    network_mode: host
